import express from 'express';
import { auth, requireAdmin } from '../middlewares/auth.js';
import * as ctl from '../controllers/catalogAdminController.js';
const r = express.Router();
r.get('/skills', ctl.listSkills);
r.get('/skills/:id', ctl.getSkill);
r.post('/skills', auth(true), requireAdmin, ctl.createSkill);
r.put('/skills/:id', auth(true), requireAdmin, ctl.updateSkill);
r.delete('/skills/:id', auth(true), requireAdmin, ctl.deleteSkill);
r.get('/levels', ctl.listLevels);
r.get('/levels/:id', ctl.getLevel);
r.post('/levels', auth(true), requireAdmin, ctl.createLevel);
r.put('/levels/:id', auth(true), requireAdmin, ctl.updateLevel);
r.delete('/levels/:id', auth(true), requireAdmin, ctl.deleteLevel);
r.get('/topics', ctl.listTopics);
r.get('/topics/:id', ctl.getTopic);
r.post('/topics', auth(true), requireAdmin, ctl.createTopic);
r.put('/topics/:id', auth(true), requireAdmin, ctl.updateTopic);
r.delete('/topics/:id', auth(true), requireAdmin, ctl.deleteTopic);
export default r;