export const USER_ROLE = ['ADMIN','LEARNER'];
export const USER_STATUS = ['ACTIVE','LOCKED'];
export const CONTENT_TYPE = ['WRITING_PROMPT','LISTENING_AUDIO','SPEAKING_PROMPT','READING_PASSAGE','GRAMMAR_EXERCISE'];
export const QUESTION_TYPE = ['MCQ','FILL_BLANK','ORDER_WORDS','OPEN_ENDED'];
export const ATTEMPT_STATUS = ['IN_PROGRESS','SUBMITTED','GRADED'];
export const ATTEMPT_SCOPE = ['CONTENT','MOCK_TEST'];
export const ARTIFACT_TYPE = ['WRITING','SPEAKING'];